/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZPrRUV51n0W
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

//use the driftreviews.svg logo from public folder
import DriftLogo from "@/../public/driftreviews.svg?react";

export function Navbar() {
  return (
    <header className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <nav className="fixed inset-x-0 top-0 z-50 bg-white shadow dark:bg-gray-950">
        <div className="container px-4 md:px-6">
          <div className="flex h-14 items-center">
            <a
              href="#"
              className="mr-auto flex items-center gap-2 text-lg font-semibold max-w-12 w-full"
            >
              <DriftLogo />
            </a>
            <nav className="ml-auto flex items-center space-x-4">
              <a
                href="#"
                className="font-medium text-sm border-b-2 border-transparent transition-colors hover:text-gray-900 hover:border-gray-100 dark:hover:text-gray-50 dark:hover:border-gray-800"
              >
                Home
              </a>
              <a
                href="#"
                className="font-medium text-sm border-b-2 border-transparent transition-colors hover:text-gray-900 hover:border-gray-100 dark:hover:text-gray-50 dark:hover:border-gray-800"
              >
                Features
              </a>
              <a
                href="#"
                className="font-medium text-sm border-b-2 border-transparent transition-colors hover:text-gray-900 hover:border-gray-100 dark:hover:text-gray-50 dark:hover:border-gray-800"
              >
                Pricing
              </a>
              <a
                href="#"
                className="font-medium text-sm border-b-2 border-transparent transition-colors hover:text-gray-900 hover:border-gray-100 dark:hover:text-gray-50 dark:hover:border-gray-800"
              >
                Contact
              </a>
            </nav>
          </div>
        </div>
      </nav>
    </header>
  );
}
