/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const MousepadLazyImport = createFileRoute('/mousepad')()
const KeyboardLazyImport = createFileRoute('/keyboard')()

// Create/Update Routes

const MousepadLazyRoute = MousepadLazyImport.update({
  path: '/mousepad',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/mousepad.lazy').then((d) => d.Route))

const KeyboardLazyRoute = KeyboardLazyImport.update({
  path: '/keyboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/keyboard.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/keyboard': {
      preLoaderRoute: typeof KeyboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/mousepad': {
      preLoaderRoute: typeof MousepadLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  KeyboardLazyRoute,
  MousepadLazyRoute,
])

/* prettier-ignore-end */
