/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const MousepadLazyImport = createFileRoute('/mousepad')()
const KeyboardLazyImport = createFileRoute('/keyboard')()

// Create/Update Routes

const MousepadLazyRoute = MousepadLazyImport.update({
  id: '/mousepad',
  path: '/mousepad',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/mousepad.lazy').then((d) => d.Route))

const KeyboardLazyRoute = KeyboardLazyImport.update({
  id: '/keyboard',
  path: '/keyboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/keyboard.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/keyboard': {
      id: '/keyboard'
      path: '/keyboard'
      fullPath: '/keyboard'
      preLoaderRoute: typeof KeyboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/mousepad': {
      id: '/mousepad'
      path: '/mousepad'
      fullPath: '/mousepad'
      preLoaderRoute: typeof MousepadLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/keyboard': typeof KeyboardLazyRoute
  '/mousepad': typeof MousepadLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/keyboard': typeof KeyboardLazyRoute
  '/mousepad': typeof MousepadLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/keyboard': typeof KeyboardLazyRoute
  '/mousepad': typeof MousepadLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/keyboard' | '/mousepad'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/keyboard' | '/mousepad'
  id: '__root__' | '/' | '/keyboard' | '/mousepad'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KeyboardLazyRoute: typeof KeyboardLazyRoute
  MousepadLazyRoute: typeof MousepadLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KeyboardLazyRoute: KeyboardLazyRoute,
  MousepadLazyRoute: MousepadLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/keyboard",
        "/mousepad"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/keyboard": {
      "filePath": "keyboard.lazy.tsx"
    },
    "/mousepad": {
      "filePath": "mousepad.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
